name: build

on: [pull_request, push] # TODO remove "push". Added it temporarily for debugging.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        push: false
